# Strip the 'v' from the version tag
{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: processlib
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - numpy
    - sip 4.19*           #For the SIP module
    - gsl 2.2*
  build:
    - git
    - cmake
    - {{ compiler('cxx') }}
    - python {{ python }} #Python is used by CMake configure stage
    - sip 4.19*           #For the SIP generator
  run:
    - python
    - numpy
    - sip 4.19*
    - gsl 2.2*

test:
  imports:
    - processlib

about:
  home: https://github.com/esrf-bliss/Processlib
  license: GPL
  license_file: COPYING
  summary: a compagnion library of LImA for basic image processing
