{% set version = "1.5.2" %}

package:
  name: processlib
  version: {{ version }}

source:
  git_url: https://gitlab.esrf.fr/limagroup/Processlib.git
  git_branch: 16-generate-conda-packages

requirements:
  build:
    - git
    - cmake
    - {{ compiler('cxx') }}
    - python {{ python }} #Python is used by CMake configure stage
    - numpy
    - sip 4.18*           #For the SIP generator
    - gsl 2.2*
  run:
    - python {{ python }}
    - numpy
    - sip 4.18*
    - gsl 2.2*

test:
  imports:
    - processlib

about:
  home: https://github.com/esrf-bliss/Processlib
  license: GPL
  license_file: COPYING
  summary: a compagnion library of LiMA for basic image processing
