# Strip the 'v' from the version tag
{% set version = GIT_DESCRIBE_TAG[1:] %}

package:
  name: processlib
  version: {{ version }}

source:
  path: ..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  host:
    - python {{ python }}
    - numpy {{ numpy }}
    - sip 4.19.8             # For compatibility with pyqt 5.9.2
    - gsl 2.2.*
  build:
    - git
    - cmake
    - {{ compiler('cxx') }}
  run:
    - python
    - numpy
    - sip >=4.19.4, <=4.19.8 # For compatibility with pyqt 5.9.2
    - {{ pin_compatible('gsl', max_pin='x.x') }}

test:
  imports:
    - processlib

about:
  home: https://github.com/esrf-bliss/Processlib
  license: GPL
  license_file: COPYING
  summary: a compagnion library of LImA for basic image processing
